sergei_k_vlad_auto33_public:
    resource: "@SergeiKVladAuto33Bundle/Resources/config/routing/public.yml"
    prefix:   /{_locale}/
    defaults: {_locale: ru}
    requirements:
        _locale: en|ru

sergei_k_vlad_auto33_locale:
    pattern: /
    defaults: {_controller: SergeiKVladAuto33Bundle:Locale:remap}

sergei_k_vlad_auto33_admin:
    resource: "@SergeiKVladAuto33Bundle/Resources/config/routing/admin.yml"
    prefix: /admin

login:
    pattern: /login
    defaults: { _controller:SergeiKVladAuto33Bundle:User:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout


# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
