<?php

namespace SergeiK\VladAuto33Bundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class UserController__JMSInjector
{
    public static function inject($container) {
        $instance = new \SergeiK\VladAuto33Bundle\Controller\UserController();
        return $instance;
    }
}
