admin_index:
    pattern: /
    defaults: {_controller:SergeiKVladAuto33Bundle:Admin:index}

admin_cars_list:
    pattern: /cars
    defaults: { _controller:SergeiKVladAuto33Bundle:Admin:carslist }

admin_new_car:
    pattern: /new_car
    defaults: { _controller:SergeiKVladAuto33Bundle:Admin:newcar }
    requirements: { _method: get }

admin_create_new_car:
    pattern: /new_car
    defaults: { _controller:SergeiKVladAuto33Bundle:Admin:createnewcar }
    requirements: { _method: post }

admin_edit_car:
    pattern: /edit_car/{id}
    defaults: { _controller:SergeiKVladAuto33Bundle:Admin:editcar }
    requirements: { _method: get }

admin_save_car:
    pattern: /edit_car/{id}
    defaults: { _controller:SergeiKVladAuto33Bundle:Admin:saveCar }
    requirements: { _method: post }

admin_delete_car:
    pattern: /delete_car/{id}
    defaults: { _controller:SergeiKVladAuto33Bundle:Admin:deleteCar }

admin_edit_booking:
    pattern: /edit_booking/{id}
    defaults: { _controller:SergeiKVladAuto33Bundle:Admin:editBooking }
    requirements: { _method: get }

admin_save_booking:
    pattern: /edit_booking/{id}
    defaults: { _controller:SergeiKVladAuto33Bundle:Admin:saveBooking }
    requirements: { _method: post }

admin_delete_booking:
    pattern: /delete_booking/{id}
    defaults: { _controller:SergeiKVladAuto33Bundle:Admin:deleteBooking }

admin_booking_archive:
    pattern: /booking_archive
    defaults: { _controller:SergeiKVladAuto33Bundle:Admin:bookingArchive }

admin_client_crud:
    resource: "@SergeiKVladAuto33Bundle/Controller/ClientController.php"
    type: annotation
    prefix: /